osd-playlist=yes
keep-open=yes
hwdec=auto-safe
interpolation=yes
tscale=oversample
video-sync=display-resample
deband=yes
deband-grain=16
save-position-on-quit=yes

autofit-larger=100%x100%

cache=yes
cache-secs=30
demuxer-max-bytes=50M

user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
ytdl-format="bestvideo[height<=?1080]+bestaudio/best"
